### ISSUE TITLE
Dependency on Composer Manager not needed

### ISSUE THREAD

**Issue by mccrodp** [RoySegall/rethinkdb#24]
Composer Manager is deprecated, but I don't think it should be a dependency anyway as you can install the packages via composer or through composer manager.

https://www.drupal.org/node/2404989

Maybe better to just add info from link above or just link to it in the README. (Sorry I didn't get a chance to make a PR). Will try out the module again soon.

**Comment by RoySegall** [comment]
Hmm.. It's deprecated but not dead :)

I'll keep use it in the mean while but I need to read about the new way to manage composer dependency.

**Comment by mccrodp** [comment]
Yep, it's required for < 8.1 anyway, so not dead :)

What I meant is:

> Note: Your module should not depend on Composer Manager. The module itself is not required to  be enabled for commands to work, and other users might use different Composer strategies that don't involve Composer Manager.

From https://www.drupal.org/node/2405811

**Comment by RoySegall** [comment]
Hmmm.. I can see what you saying.

**Comment by RoySegall** [comment]
Removed. I'll handle #23 for now and set up a nicer install process.
